// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpifhscsvniqosejsozd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1waWZoc2Nzdm5pcW9zZWpzb3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzM0NDgsImV4cCI6MjA3MDMwOTQ0OH0.d9Qrz-7u7H1x0mWk2dUC6QtBeK0ipVJDy1cVRSXK3kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});